export type PlatformId =
  | 'youtube'
  | 'tiktok'
  | 'facebook'
  | 'instagram'
  | 'twitter'
  | 'spotify'
  | 'soundcloud'
  | 'pinterest'
  | 'vimeo'
  | 'reddit'
  | 'twitch'
  | 'dailymotion'
  | 'generic';

export type MediaCategory = 'video' | 'audio' | 'playlist' | 'photo';

export interface ServerMediaFormat {
  id: string;
  label: string;
  quality: string;
  extension: 'mp4' | 'webm' | 'mp3' | 'm4a' | 'wav' | 'srt' | 'vtt';
  type: 'video' | 'audio' | 'subtitle';
  resolution?: string;
  filesize?: string;
  filesizeBytes?: number;
  bitrate?: string;
  fps?: number;
  hasAudio?: boolean;
  sourceFormatId?: string;
  sourceExtension?: string;
  videoCodec?: string;
  audioCodec?: string;
  formatNote?: string;
  protocol?: string;
  dynamicRange?: string;
  language?: string;
  isAutoGenerated?: boolean;
  watermarkFree?: boolean;
  recommended?: boolean;
  tier?: 'best_quality' | 'best_balance' | 'smallest_size';
}

export interface ServerPlaylistItem {
  id: string;
  index: number;
  title: string;
  author: string;
  duration: string;
  durationSeconds: number;
  thumbnailUrl: string;
  url: string;
  filesizeEst?: string;
  selected?: boolean;
}

export interface ServerMediaMetadata {
  url: string;
  title: string;
  author: string;
  authorUrl?: string;
  platform: PlatformId;
  category: MediaCategory;
  thumbnailUrl: string;
  duration?: string;
  durationSeconds?: number;
  uploadDate?: string;
  views?: string;
  likes?: string;
  description?: string;
  formats: ServerMediaFormat[];
  subtitles?: {
    language: string;
    langCode: string;
    format: 'srt' | 'vtt';
    isAutoGenerated: boolean;
    url?: string;
  }[];
  playlist?: {
    title: string;
    totalItems: number;
    totalDuration: string;
    items: ServerPlaylistItem[];
  };
}

export interface DownloadResult {
  filePath?: string;
  stream?: NodeJS.ReadableStream;
  fileName: string;
  mimeType: string;
  contentLength?: number;
}
